#!/usr/bin/env python3
"""Emit VehicleClassSizeCatalogue.generated.swift from Resources/vehicle_size_matrix.md CSV block."""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "Resources" / "vehicle_size_matrix.md"
OUT_PATH = (
    ROOT
    / "Sources/GuardianHQ/Systems/Utilities/Fleet/VehicleClassSizeCatalogue.generated.swift"
)

CLASS_TO_FLEET_TYPE = {
    "UAV-C Copter": "uavCopter",
    "UAV-F Fixed Wing": "uavFixedWing",
    "UAV-F VTOL": "uavVTOL",
    "UGV-W Wheeled": "ugvWheeled",
    "UGV-T Tracked": "ugvTracked",
    "UGV-L Legged": "ugvLegged",
    "USV": "usv",
    "UUV": "uuv",
}

TIER_ORDER = ["micro", "mini", "small", "medium", "large", "xlarge", "xxlarge"]


def midpoint_cm(range_token: str) -> int:
    token = range_token.strip().replace(",", "")
    if "-" not in token:
        raise ValueError(f"expected min-max range, got {range_token!r}")
    lo_s, hi_s = token.split("-", 1)
    lo, hi = int(lo_s), int(hi_s)
    return int(round((lo + hi) / 2))


def parse_csv_block(text: str) -> list[tuple[str, str, int, int, int]]:
    match = re.search(r"```csv\n(.*?)```", text, re.DOTALL)
    if not match:
        raise SystemExit("vehicle_size_matrix.md: missing ```csv block")
    rows: list[tuple[str, str, int, int, int]] = []
    for line in match.group(1).strip().splitlines():
        line = line.strip()
        if not line or line.startswith("class,"):
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) != 5:
            raise SystemExit(f"bad csv row: {line!r}")
        cls, tier, w, l, h = parts
        if tier not in TIER_ORDER:
            raise SystemExit(f"unknown tier {tier!r} in {line!r}")
        fleet = CLASS_TO_FLEET_TYPE.get(cls)
        if fleet is None:
            raise SystemExit(f"unknown class {cls!r} in {line!r}")
        rows.append((fleet, tier, midpoint_cm(w), midpoint_cm(l), midpoint_cm(h)))
    return rows


def emit(rows: list[tuple[str, str, int, int, int]], matrix_hash: str) -> str:
    lines = [
        "// Generated by scripts/generate_vehicle_class_size_catalogue.py — do not edit.",
        f"// Source: Resources/vehicle_size_matrix.md (sha256 prefix {matrix_hash})",
        "",
        "import Foundation",
        "",
        "enum VehicleClassSizeCatalogueGenerated {",
        f'  static let matrixSHA256Prefix = "{matrix_hash}"',
        "",
        "  static let entries: [VehicleClassSizeCatalogue.Entry] = [",
    ]
    for fleet, tier, w, l, h in rows:
        lines.append(
            f"    .init(vehicleClass: .{fleet}, tier: .{tier}, "
            f"widthCm: {w}, lengthCm: {l}, heightCm: {h}),"
        )
    lines.append("  ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = MATRIX_PATH.read_text(encoding="utf-8")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
    rows = parse_csv_block(text)
    expected = len(CLASS_TO_FLEET_TYPE) * len(TIER_ORDER)
    if len(rows) != expected:
        raise SystemExit(f"expected {expected} rows, got {len(rows)}")
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(emit(rows, digest), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(rows)} entries, hash {digest})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
